export const cronSections = [
  {
    id: "high-frequency",
    title: "高频任务",
    note: "全天巡航类任务，主要负责流量快报和异常发现。",
    tasks: [
      {
        id: "umami-report",
        label: "Umami Monitoring Digest",
        code: "*/30 · 全天每30分钟",
        note: "抓 10 个 repo 的 Umami 数据并发飞书快报。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/umami-report.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/umami-report.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/umami-report.yml",
        ref: "main",
      },
    ],
  },
  {
    id: "daily",
    title: "日频任务",
    note: "每天固定时间触发的核心监控。",
    tasks: [
      {
        id: "reddit-scan",
        label: "AIGC Reddit Daily Scan",
        code: "09:00",
        note: "抓 8 个 AIGC Reddit 社区热帖并推送摘要。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/aigc-reddit-scan.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/aigc-reddit-scan.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/aigc-reddit-scan.yml",
        ref: "main",
      },
      {
        id: "sitemap-check",
        label: "Sitemap Continuous Validation",
        code: "10:00",
        note: "站点地图持续验证（静态分析 + HTTP 检查）。",
        repo: "Sliense-ysd/actionfigure-generator",
        workflowFile: ".github/workflows/sitemap-check.yml",
        workflowUrl: "https://github.com/Sliense-ysd/actionfigure-generator/actions/workflows/sitemap-check.yml",
        sourceUrl: "https://github.com/Sliense-ysd/actionfigure-generator/blob/main/.github/workflows/sitemap-check.yml",
        ref: "main",
      },
      {
        id: "anti-abuse",
        label: "Anti Abuse Daily Scan",
        code: "11:20",
        note: "每日风控巡检，重点看异常使用模式。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/anti-abuse-scan.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/anti-abuse-scan.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/anti-abuse-scan.yml",
        ref: "main",
      },
      {
        id: "domain-auction",
        label: "Domain Auction Monitor",
        code: "19:00",
        note: "每晚扫描多来源过期/拍卖域名并做 authority 评估。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/domain-auction-monitor.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/domain-auction-monitor.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/domain-auction-monitor.yml",
        ref: "main",
      },
      {
        id: "daily-digest",
        label: "Daily Data Digest",
        code: "21:00",
        note: "生成注册、付费、留存等每日数据汇总。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/daily-digest.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/daily-digest.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/daily-digest.yml",
        ref: "main",
      },
      {
        id: "trend-scan",
        label: "Trend Keyword Scan",
        code: "22:00",
        note: "监控 Google Trends 暴涨关键词。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/trend-scan.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/trend-scan.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/trend-scan.yml",
        ref: "main",
      },
      {
        id: "nutstore-backup",
        label: "ai-shared Nutstore Backup",
        code: "02:00 (+1)",
        note: "rclone 同步 ai-shared 到坚果云。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/github-cron-backup.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/github-cron-backup.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/github-cron-backup.yml",
        ref: "main",
      },
    ],
  },
  {
    id: "event-driven",
    title: "事件驱动任务",
    note: "默认不按 cron 跑，但也是你会频繁回看的监控动作。",
    tasks: [
      {
        id: "sitemap-monitor",
        label: "Sitemap Competitor Monitor",
        code: "manual",
        note: "竞对 sitemap 手动监控，状态放在 GitHub Release 里。",
        repo: "Sliense-ysd/cron-hub",
        workflowFile: ".github/workflows/sitemap-monitor.yml",
        workflowUrl: "https://github.com/Sliense-ysd/cron-hub/actions/workflows/sitemap-monitor.yml",
        sourceUrl: "https://github.com/Sliense-ysd/cron-hub/blob/main/.github/workflows/sitemap-monitor.yml",
        ref: "main",
      },
      {
        id: "post-deploy-search-sync",
        label: "Post-Deploy Search Sync",
        code: "workflow_run",
        note: "部署完成后自动提 sitemap 到 Google / Bing / IndexNow。",
        repo: "Sliense-ysd/nanobanana-pro-org",
        workflowFile: ".github/workflows/post-deploy-search-sync.yml",
        workflowUrl: "https://github.com/Sliense-ysd/nanobanana-pro-org/actions/workflows/post-deploy-search-sync.yml",
        sourceUrl: "https://github.com/Sliense-ysd/nanobanana-pro-org/blob/main/.github/workflows/post-deploy-search-sync.yml",
        ref: "main",
      },
    ],
  },
];

export const cronTasks = cronSections.flatMap((section) => section.tasks);
