window.FUNNEL_SNAPSHOTS = {
  songunique: {
    mode: "native",
    window: "最近 7 天",
    source:
      "Umami · songunique.com 独立 website · session 去重 · 顺序漏斗",
    updatedAt: "2026-04-20",
    totals: {
      sessionsWithCustomEvents: 219,
      homepageSessions: 192,
      paymentSuccessSessions: 3,
      overallRate: 1.6,
    },
    summaryStats: [
      { label: "口径", value: "最近 7 天" },
      { label: "主链路成功", value: "3" },
      { label: "首页到成功", value: "1.6%" },
    ],
    hero: {
      title: "SongUnique",
      subtitle:
        "目前最该盯的不是支付技术成功率，而是首页首屏到 CTA、以及 checkout 页到 payment click 的心理摩擦。",
      pills: [
        "主链路已定义",
        "顺序 session funnel",
        "可直接行动",
      ],
    },
    stages: [
      { id: "homepage_view", label: "首页曝光", count: 192 },
      { id: "hero_cta_click", label: "首屏 CTA 点击", count: 41 },
      { id: "ts_form_complete", label: "表单完成", count: 19 },
      { id: "checkout_page_view", label: "结账页曝光", count: 18 },
      { id: "payment_click", label: "支付点击", count: 7 },
      { id: "checkout_redirect", label: "跳转支付", count: 6 },
      { id: "payment_success", label: "支付成功", count: 3 },
    ],
    conversions: [
      {
        id: "landing-to-cta",
        label: "首页 → CTA",
        rate: 21.4,
        numerator: 41,
        denominator: 192,
        tone: "warn",
        note: "首屏把人送进 create 的能力偏弱，是第一处大漏点。",
      },
      {
        id: "cta-to-form",
        label: "CTA → 表单完成",
        rate: 46.3,
        numerator: 19,
        denominator: 41,
        tone: "info",
        note: "多步表单整体可接受，但还没拆到 step 级流失。",
      },
      {
        id: "form-to-checkout",
        label: "表单完成 → 结账页",
        rate: 94.7,
        numerator: 18,
        denominator: 19,
        tone: "success",
        note: "表单完成后基本都能顺利到 complete-order。",
      },
      {
        id: "checkout-to-payclick",
        label: "结账页 → 支付点击",
        rate: 38.9,
        numerator: 7,
        denominator: 18,
        tone: "warn",
        note: "这是当前第二个大漏点，更像文案/信任/价格心理问题。",
      },
      {
        id: "payclick-to-redirect",
        label: "支付点击 → 跳转支付",
        rate: 85.7,
        numerator: 6,
        denominator: 7,
        tone: "success",
        note: "按钮点击后的前端/服务端链路总体可用，不是主漏点。",
      },
      {
        id: "redirect-to-success",
        label: "跳转支付 → 支付成功",
        rate: 50.0,
        numerator: 3,
        denominator: 6,
        tone: "info",
        note: "有流失，但量级暂时低于 checkout 页心理摩擦的影响。",
      },
    ],
    diagnostics: [
      {
        label: "checkout_page_view 唯一 session",
        value: "44",
        note: "高于 hero CTA 的 42，说明存在回访/直达 checkout 流量。",
      },
      {
        label: "payment_click 唯一 session",
        value: "12",
        note: "原始事件 48 次，重复点击很多，不能直接看 raw count。",
      },
      {
        label: "ts_checkout_start 唯一 session",
        value: "11",
        note: "支付点击之后大多能进入真正的 checkout 启动。",
      },
      {
        label: "checkout_error 唯一 session",
        value: "6",
        note: "确实有技术失败，但目前不是最大结构性漏点。",
      },
      {
        label: "payment_incomplete 唯一 session",
        value: "3",
        note: "支付中断存在，但总体量级仍低于 checkout 页未点击支付。",
      },
      {
        label: "payment_success / checkout_status",
        value: "7 / 7",
        note: "成功页与 checkout status 当前对齐，成功回写链路是通的。",
      },
    ],
    insights: [
      "首页到 Hero CTA 只有 21.4%，说明首屏 promise 和按钮驱动力还不够强。",
      "checkout_page_view 到 payment_click 只有 38.9%，当前最值得优先优化的是 complete-order 页。",
      "支付点击后的技术路径并不差：payment_click → ts_checkout_start → checkout_redirect 基本顺畅。",
      "raw event count 已经明显失真，所以站点漏斗必须默认使用顺序 session 口径。",
    ],
    nextActions: [
      "优先优化首页 Hero 的 promise、social proof 和 CTA 文案。",
      "再优化 complete-order 页的信任、交付承诺和价格心理承接。",
      "下一轮把 ts_form_step_* 拆成 step 级报表，定位表单具体卡点。",
    ],
    links: [
      { label: "用户路径", href: "/journeys/" },
      { label: "Umami", href: "https://analytics.seekorigin.ai/" },
      { label: "Clarity", href: "https://clarity.microsoft.com/projects" },
      { label: "Create", href: "https://songunique.com/create" },
      { label: "结账页", href: "https://songunique.com/complete-order" },
      {
        label: "未交付订单",
        href: "https://musicmake.ai/admin/music-orders?orderType=testimony",
      },
    ],
  },
  musicmake: {
    mode: "native",
    window: "最近 7 天",
    source:
      "Umami · musicmake.ai 独立 website · 排除 /admin · session 去重 · 顺序漏斗",
    updatedAt: "2026-04-25",
    totals: {
      sessionsWithCustomEvents: 348,
      generateSubmitSessions: 114,
      generateSuccessSessions: 83,
      checkoutRedirectSessions: 4,
      overallRate: 72.8,
    },
    summaryStats: [
      { label: "口径", value: "最近 7 天" },
      { label: "提交到成功", value: "72.8%" },
      { label: "成功后播放", value: "63" },
    ],
    hero: {
      title: "MusicMake",
      subtitle:
        "MusicMake 不能只看一条支付漏斗，要拆成生成激活、阻断转付费、定价支付三段。当前生成后体验可用，主要断点在入口提交和被阻断后的升级承接。",
      pills: ["三段漏斗", "顺序 session funnel", "排除后台流量"],
    },
    stages: [
      { id: "music_generate_submit", label: "提交生成", count: 114 },
      { id: "music_generate_success", label: "生成成功", count: 83 },
      { id: "music_player_play", label: "开始播放", count: 63 },
      { id: "music_result_action", label: "深度操作", count: 35 },
    ],
    conversions: [
      {
        id: "submit-to-success",
        label: "提交生成 → 生成成功",
        rate: 72.8,
        numerator: 83,
        denominator: 114,
        tone: "success",
        note: "生成链路本身不是最大问题，不能再用过窄入口口径把成功率看低。",
      },
      {
        id: "success-to-play",
        label: "生成成功 → 开始播放",
        rate: 75.9,
        numerator: 63,
        denominator: 83,
        tone: "success",
        note: "成功后大部分用户会试听，说明结果消费链路是可用的。",
      },
      {
        id: "play-to-action",
        label: "开始播放 → 深度操作",
        rate: 55.6,
        numerator: 35,
        denominator: 63,
        tone: "info",
        note: "下一步要拆 action=download/share/extend/edit，当前只看到聚合后的深度操作。",
      },
    ],
    subFunnels: [
      {
        title: "入口到提交诊断",
        subtitle:
          "只看可识别入口曝光后的顺序路径，避免把直接进入表单的会话混进入口问题。",
        stages: [
          { id: "creative_entry", label: "可识别入口", count: 153 },
          { id: "music_generate_submit", label: "提交生成", count: 52 },
          { id: "music_generate_success", label: "生成成功", count: 32 },
        ],
        conversions: [
          {
            label: "可识别入口 → 提交生成",
            rate: 34.0,
            numerator: 52,
            denominator: 153,
            tone: "warn",
            note: "入口页把用户推到首次提交的能力偏弱，需要按页面/来源拆开看。",
          },
          {
            label: "提交生成 → 生成成功",
            rate: 61.5,
            numerator: 32,
            denominator: 52,
            tone: "info",
            note: "入口来源进入的用户成功率低于直接提交用户，可能和新用户/低意图流量有关。",
          },
        ],
      },
      {
        title: "阻断转付费漏斗",
        subtitle:
          "看积分/会员阻断后是否被顺利带到升级意图，这是 MusicMake 当前最关键的桥。",
        stages: [
          { id: "music_generate_blocked", label: "生成被阻断", count: 42 },
          { id: "member_hint_modal_view", label: "提示弹窗曝光", count: 41 },
          { id: "upgrade_intent", label: "升级/购买意图", count: 1 },
          { id: "pricing_or_credits_view", label: "定价/积分页", count: 1 },
        ],
        conversions: [
          {
            label: "被阻断 → 提示曝光",
            rate: 97.6,
            numerator: 41,
            denominator: 42,
            tone: "success",
            note: "弹窗基本能出现，问题不在触发。",
          },
          {
            label: "提示曝光 → 升级意图",
            rate: 2.4,
            numerator: 1,
            denominator: 41,
            tone: "warn",
            note: "最大断点：被阻断后几乎没有继续升级，需要重做 paywall 承接。",
          },
          {
            label: "升级意图 → 定价/积分页",
            rate: 100.0,
            numerator: 1,
            denominator: 1,
            tone: "info",
            note: "量级太小，只能说明点击后的跳转基本能到达。",
          },
        ],
      },
      {
        title: "变现子漏斗",
        subtitle: "把已经进入定价/积分页的会话继续送到支付结果。",
        stages: [
          { id: "pricing_or_credits_view", label: "查看定价/积分", count: 28 },
          { id: "checkout_click", label: "点击结账", count: 9 },
          { id: "checkout_redirect", label: "跳转支付", count: 4 },
          { id: "checkout_status", label: "支付结果", count: 0 },
        ],
        conversions: [
          {
            label: "定价/积分页 → 点击结账",
            rate: 32.1,
            numerator: 9,
            denominator: 28,
            tone: "warn",
            note: "进入定价后仍有明显犹豫，但弱点小于 blocked 弹窗承接。",
          },
          {
            label: "点击结账 → 跳转支付",
            rate: 44.4,
            numerator: 4,
            denominator: 9,
            tone: "warn",
            note: "有一半以上 checkout click 没串到 redirect，要继续看 provider / session 创建细节。",
          },
          {
            label: "跳转支付 → 支付结果",
            rate: 0.0,
            numerator: 0,
            denominator: 4,
            tone: "warn",
            note: "最近 7 天当前口径没有 checkout_status，末端应补服务端成功信号。",
          },
        ],
      },
    ],
    diagnostics: [
      {
        label: "custom event 唯一 session",
        value: "348",
        note: "本次快照已排除 /admin，避免后台操作污染产品漏斗。",
      },
      {
        label: "入口曝光组合",
        value: "lp 94 / music 77 / generator 99",
        note: "入口不是单一首页，BPS 不能只用 generator_section_view 当主入口。",
      },
      {
        label: "submit / success 直接唯一 session",
        value: "114 / 103",
        note: "直接看事件集合，生成成功量不低；主链路应按顺序 session 解释。",
      },
      {
        label: "blocked / fail 唯一 session",
        value: "42 / 12",
        note: "阻断比失败更影响变现承接，技术失败不是第一问题。",
      },
      {
        label: "member_hint_view / upgrade_click",
        value: "103 / 9",
        note: "全量弹窗有升级点击，但 blocked 顺序链路只串到 1，说明桥接字段和承接都要补。",
      },
      {
        label: "pricing_or_credits / checkout_click",
        value: "28 / 9",
        note: "定价页点击率约 32.1%，还需要按 plan、billing、source 拆。",
      },
      {
        label: "checkout_redirect / checkout_status",
        value: "5 / 0",
        note: "能看到跳转，但前端结果页没有形成成功信号；需要服务端支付成功补点。",
      },
      {
        label: "payment_incomplete 唯一 session",
        value: "1",
        note: "支付中断量小，但没有 provider/errorCode 级解释，诊断能力仍不足。",
      },
    ],
    insights: [
      "旧口径把生成器曝光作为唯一入口，会低估真实生成成功率；主链路应先看 submit → success → play。",
      "当前最大断点不是生成引擎，而是被阻断后的付费承接：42 个 blocked 只有 1 个顺序进入升级意图。",
      "定价页到结账点击为 32.1%，需要优化方案表达，但它不是第一断点。",
      "checkout_status 最近 7 天为 0，末端不能只依赖前端回跳页，需要服务端支付成功事件兜底。",
      "下载/分享没有形成独立事件，结果消费只能先用 music_player_action 聚合解释。",
    ],
    nextActions: [
      "优先重做阻断弹窗的价值承接：明确剩余额度、解锁结果、推荐套餐、继续生成的下一步。",
      "给 member_hint_* 统一补 sourceEvent / triggerReason / targetPlan / cta / modalVariant，BPS 才能串起阻断 → 定价。",
      "把 checkout_status 拆成 success / failed / timeout，并补服务端 payment_success，避免用户不回跳导致漏记。",
      "把 music_player_action 按 action=download/share/extend/edit 拆出 BPS 诊断，或补独立 download/share 事件。",
      "按入口页、utm、locale 分拆入口 → submit，不要把首页、SEO 工具页、直接生成页混在一个入口指标里。",
    ],
    links: [
      { label: "用户路径", href: "/journeys/" },
      {
        label: "分析仪表盘",
        href: "https://musicmake.ai/admin/analytics-dashboard",
      },
      {
        label: "站点转化（旧页）",
        href: "https://musicmake.ai/admin/site-conversion",
      },
      { label: "Umami", href: "https://analytics.seekorigin.ai/" },
      {
        label: "音乐订单",
        href: "https://musicmake.ai/admin/music-orders",
      },
    ],
  },
};

window.SITE_CONVERSION_OVERVIEW = {
  mode: "native_snapshot",
  title: "站点转化总览",
  source:
    "MusicMake admin/site-conversion · production DB + Umami · 只展示聚合数据",
  updatedAt: "2026-04-25",
  generatedAt: "2026-04-25T02:47:01.919Z",
  window: "最近 30 天",
  dateRange: {
    startDate: "2026-03-27",
    endDate: "2026-04-25",
  },
  totals: {
    uniqueVisitors: 4024,
    checkoutActors: 30,
    paidOrderUsers: 43,
    paidOrderCount: 47,
    paidRevenueCents: 359860,
    overallConversionRate: 1.1,
  },
  summaryStats: [
    { label: "独立访客", value: "4,024" },
    { label: "下单人数", value: "43" },
    { label: "成功订单", value: "47" },
    { label: "收入", value: "$3,598.60" },
    { label: "整体转化率", value: "1.1%" },
  ],
  highlights: [
    {
      label: "收入最高",
      site: "songunique.com",
      value: "$1,560.98",
      note: "30 天内 13 笔成功订单，站点收入领先。",
    },
    {
      label: "访客最多",
      site: "musicmake.ai",
      value: "3,242",
      note: "主站流量最大，但访客到 checkout 只有 0.9%。",
    },
    {
      label: "归因风险",
      site: "custom song sites",
      value: "18 条提醒",
      note: "多个故事歌曲站点有订单但缺 tracking_session 起点。",
    },
  ],
  siteSummaries: [
    {
      siteKey: "songunique.com",
      label: "songunique.com",
      sourceDb: "musicmake",
      uniqueVisitors: 782,
      checkoutActors: 0,
      paidOrderUsers: 12,
      paidOrderCount: 13,
      paidRevenueCents: 156098,
      visitorToCheckoutRate: 0,
      conversionRate: 1.5,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-21T00:06:04.081Z",
      note: "成功订单集中，但 payment_attribution 未记录 checkout 起点。",
    },
    {
      siteKey: "musicmake.ai",
      label: "musicmake.ai",
      sourceDb: "musicmake",
      uniqueVisitors: 3242,
      checkoutActors: 30,
      paidOrderUsers: 18,
      paidOrderCount: 19,
      paidRevenueCents: 86963,
      visitorToCheckoutRate: 0.9,
      conversionRate: 0.6,
      checkoutCompletionRate: 60,
      latestVisitAt: "2026-04-25 02:12:04.981",
      latestPaidAt: "2026-04-24T08:42:28.201Z",
      note: "主站访客最多，付费承接仍弱于生成激活。",
    },
    {
      siteKey: "nanobanana-sites",
      label: "nanobanana 站群",
      sourceDb: "gempix-ai",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 4,
      paidOrderCount: 4,
      paidRevenueCents: 0,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-23T15:58:12.840Z",
      note: "共享库订单只能归到站群池，金额映射仍不完整。",
    },
    {
      siteKey: "wifesong.com",
      label: "wifesong.com",
      sourceDb: "musicmake",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 2,
      paidOrderCount: 2,
      paidRevenueCents: 19800,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-02T20:21:39.152Z",
      note: "订单归因明确，但访客起点缺失。",
    },
    {
      siteKey: "blessingsong.org",
      label: "blessingsong.org",
      sourceDb: "musicmake",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 2,
      paidOrderCount: 3,
      paidRevenueCents: 29700,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-02T20:21:38.825Z",
      note: "订单归因明确，但访客起点缺失。",
    },
    {
      siteKey: "mothersong.net",
      label: "mothersong.net",
      sourceDb: "musicmake",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 1,
      paidOrderCount: 2,
      paidRevenueCents: 27699,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-02T20:21:38.930Z",
      note: "订单归因明确，但访客起点缺失。",
    },
    {
      siteKey: "memorysong.org",
      label: "memorysong.org",
      sourceDb: "musicmake",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 1,
      paidOrderCount: 1,
      paidRevenueCents: 9900,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-02T20:21:38.583Z",
      note: "订单归因明确，但访客起点缺失。",
    },
    {
      siteKey: "husbandsong.org",
      label: "husbandsong.org",
      sourceDb: "musicmake",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 1,
      paidOrderCount: 1,
      paidRevenueCents: 9900,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-02T20:21:38.430Z",
      note: "订单归因明确，但访客起点缺失。",
    },
    {
      siteKey: "fathersong.org",
      label: "fathersong.org",
      sourceDb: "musicmake",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 1,
      paidOrderCount: 1,
      paidRevenueCents: 9900,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-02T20:21:38.292Z",
      note: "订单归因明确，但访客起点缺失。",
    },
    {
      siteKey: "amensong.org",
      label: "amensong.org",
      sourceDb: "musicmake",
      uniqueVisitors: 0,
      checkoutActors: 0,
      paidOrderUsers: 1,
      paidOrderCount: 1,
      paidRevenueCents: 9900,
      visitorToCheckoutRate: 0,
      conversionRate: 0,
      checkoutCompletionRate: 0,
      latestPaidAt: "2026-04-02T20:21:37.348Z",
      note: "订单归因明确，但访客起点缺失。",
    },
  ],
  risks: [
    "songunique.com 存在成功订单，但 payment_attribution 没记录 checkout 起点，结账漏斗可能不完整。",
    "多个故事歌曲站点有支付订单但 tracking_session 没有访客数据，站点转化率会显示为 0。",
    "nanobanana 站群仍只能归到 shared pool，无法精确分配到单个站点。",
    "BPS 静态页不展示最近订单明细，避免把下单人标识写进公开静态资源。",
  ],
  links: [
    {
      label: "打开后台实时页",
      href: "https://musicmake.ai/admin/site-conversion",
    },
    { label: "MusicMake 漏斗", href: "/funnels/#musicmake" },
    { label: "Umami", href: "https://analytics.seekorigin.ai/" },
  ],
};
